using Rex.Shared.Prototypes;

namespace Rex.Shared.Tests.Prototypes;

// Autogenerated prototype id strings from type names.
public sealed class PrototypeUtilityTests
{
    [Fact]
    // Plain type names become camelCase.
    public void CalculatePrototypeName_lowercases_first_letter_without_suffix()
    {
        Assert.Equal("foo", PrototypeUtility.CalculatePrototypeName("Foo"));
        Assert.Equal("playerController", PrototypeUtility.CalculatePrototypeName("PlayerController"));
    }

    [Fact]
    // Trailing Prototype is removed before camelCase.
    public void CalculatePrototypeName_strips_Prototype_suffix_before_casing()
    {
        Assert.Equal("foo", PrototypeUtility.CalculatePrototypeName("FooPrototype"));
        Assert.Equal("player", PrototypeUtility.CalculatePrototypeName("PlayerPrototype"));
    }

    [Fact]
    // Suffix constant is stable.
    public void PrototypeNameEnding_constant_matches_expected()
    {
        Assert.Equal("Prototype", PrototypeUtility.PrototypeNameEnding);
    }
}
