namespace Rex.Shared.Analyzers;

/// <summary>
///     Tells analyzers the type is codegen output so rules for authored types can skip it (access checks are the common case).
/// </summary>
/// <remarks>
///     Do not add by hand. It mutes many useful warnings and belongs on generated types only.
/// </remarks>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Interface)]
public sealed class RexAutoGeneratedAttribute : Attribute { }
