#nullable enable
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Rex.Roslyn.Shared;
using Rex.Shared.Prototypes;
using static Rex.Roslyn.Shared.Diagnostics;

namespace Rex.Analyzers;

[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class PrototypeAnalyzer : DiagnosticAnalyzer
{
    public static readonly DiagnosticDescriptor PrototypeRedundantTypeRule = new(
        IdPrototypeRedundantType,
        "Redundant Prototype Type specification",
        "Prototype {0} has explicitly set type \"{1}\" that matches autogenerated value",
        "Usage",
        DiagnosticSeverity.Warning,
        true,
        "Remove the redundant type specification."
    );

    public static readonly DiagnosticDescriptor PrototypeEndsWithPrototypeRule = new(
        IdPrototypeEndsWithPrototype,
        "Prototype name must end with the word Prototype",
        "Prototype {0} does not end with the word Prototype",
        "Usage",
        DiagnosticSeverity.Error,
        true,
        "Add the word Prototype to the end of the class name or manually specify a name in the Prototype attribute."
    );

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        [PrototypeRedundantTypeRule, PrototypeEndsWithPrototypeRule];

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.Analyze |
                                               GeneratedCodeAnalysisFlags.ReportDiagnostics);
        context.EnableConcurrentExecution();

        context.RegisterCompilationStartAction(static ctx =>
        {
            INamedTypeSymbol? prototypeAttribute =
                ctx.Compilation.GetTypeByMetadataName("Rex.Shared.Prototypes.PrototypeAttribute");

            // No attribute, no analyzer.
            if (prototypeAttribute is null)
            {
                return;
            }

            ctx.RegisterSyntaxNodeAction(
                symCtx => AnalyzePrototype(symCtx, prototypeAttribute),
                SyntaxKind.ClassDeclaration);
        });
    }

    private static void AnalyzePrototype(SyntaxNodeAnalysisContext context, INamedTypeSymbol prototypeAttributeSymbol)
    {
        if (context.Node is not ClassDeclarationSyntax classDeclarationSyntax)
        {
            return;
        }

        INamedTypeSymbol? classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax);
        if (classSymbol is null)
        {
            return;
        }

        string className = classSymbol.Name;

        if (!AttributeHelper.HasAttribute(classSymbol, prototypeAttributeSymbol, out AttributeData? attributeData))
        {
            return;
        }

        AttributeSyntax? prototypeAttribute = GetAttributeSyntax(attributeData, classDeclarationSyntax);
        if (prototypeAttribute == null)
        {
            return;
        }

        // Check for autogenerated type
        if (prototypeAttribute.ArgumentList?.Arguments[0] is not { } argumentSyntax)
        {
            if (!className.EndsWith(PrototypeUtility.PrototypeNameEnding))
            {
                context.ReportDiagnostic(Diagnostic.Create(PrototypeEndsWithPrototypeRule,
                    classDeclarationSyntax.Identifier.GetLocation(),
                    className));
            }

            return;
        }

        // We only care about redundancy if the argument is a string literal.
        // Passing in a value that resolves to a redundant string is fine.
        if (argumentSyntax.Expression is not LiteralExpressionSyntax literalSyntax)
        {
            return;
        }

        Optional<object?> literalValue = context.SemanticModel.GetConstantValue(literalSyntax);
        if (literalValue.Value is not string specifiedName)
        {
            return;
        }

        string autoName = PrototypeUtility.CalculatePrototypeName(className);

        // Check for name redundancy
        if (autoName == specifiedName)
        {
            // If the class name does not end with "Prototype", allow the redundancy
            if (!className.EndsWith(PrototypeUtility.PrototypeNameEnding))
            {
                return;
            }

            Location location = argumentSyntax.GetLocation();
            context.ReportDiagnostic(Diagnostic.Create(PrototypeRedundantTypeRule,
                location,
                className,
                specifiedName));
        }
    }

    private static AttributeSyntax? GetAttributeSyntax(
        AttributeData attributeData,
        ClassDeclarationSyntax classSyntax)
    {
        if (attributeData.ApplicationSyntaxReference is not { } syntaxReference)
        {
            return null;
        }

        foreach (AttributeListSyntax attributeList in classSyntax.AttributeLists)
        {
            foreach (AttributeSyntax attribute in attributeList.Attributes)
            {
                if (syntaxReference.SyntaxTree != attribute.SyntaxTree)
                {
                    continue;
                }

                if (!syntaxReference.Span.OverlapsWith(attribute.Span))
                {
                    continue;
                }

                return attribute;
            }
        }

        return null;
    }
}
